[package]
name = "psychopath"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]

[features]
simd_perf = ["simd"]

[profile.release]
debug = true

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
nom = "1.2"
scoped_threadpool = "0.1"
crossbeam = "0.2"
num_cpus = "0.2"
quickersort = "2.0"
lodepng = "0.8"

simd = { version = "0.1.1", optional = true }