[workspace]
members = [
    "sub_crates/float4",
    "sub_crates/halton",
    "sub_crates/math3d",
    "sub_crates/mem_arena",
    "sub_crates/sobol",
    "sub_crates/spectra_xyz"
]

[package]
name = "psychopath"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]

[features]
simd_perf = ["float4/simd_perf", "math3d/simd_perf"]

[profile.release]
debug = true

[dependencies]
# Crates.io dependencies
clap = "2.23"
crossbeam = "0.2"
half = "1.0"
lazy_static = "0.2"
nom = "1.2"
num_cpus = "1.0"
openexr = "0.5.0"
png_encode_mini = "0.1.2"
rustc-serialize = "0.3"
scoped_threadpool = "0.1"
time = "0.1"

# Local crate dependencies
[dependencies.float4]
path = "sub_crates/float4"

[dependencies.halton]
path = "sub_crates/halton"

[dependencies.math3d]
path = "sub_crates/math3d"

[dependencies.mem_arena]
path = "sub_crates/mem_arena"

[dependencies.sobol]
path = "sub_crates/sobol"

[dependencies.spectra_xyz]
path = "sub_crates/spectra_xyz"