[workspace]
members = ["sub_crates/mem_arena", "sub_crates/halton", "sub_crates/spectra_xyz"]

[package]
name = "psychopath"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]

[features]
simd_perf = ["simd"]

[profile.release]
debug = true

[dependencies]
# Crates.io dependencies
time = "0.1"
clap = "2.23"
rustc-serialize = "0.3"
nom = "1.2"
scoped_threadpool = "0.1"
crossbeam = "0.2"
num_cpus = "1.0"
lodepng = "0.8"
lazy_static = "0.2"
simd = { version = "0.2.0", optional = true }

# Github dependencies
openexr = { git = "https://github.com/cessen/openexr-rs", rev = "612fc6c81c031970ffddcab15509236711613de8" }

# Local crate dependencies
[dependencies.halton]
path = "sub_crates/halton"

[dependencies.mem_arena]
path = "sub_crates/mem_arena"

[dependencies.spectra_xyz]
path = "sub_crates/spectra_xyz"