[package]
name = "spectral_upsampling"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
edition = "2018"
license = "MIT"

[lib]
name = "spectral_upsampling"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.0"

# Local crate dependencies
[dependencies.float4]
path = "../float4"