[package]
name = "math3d"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
edition = "2018"
license = "MIT, Apache 2.0"

[lib]
name = "math3d"
path = "src/lib.rs"

# Local crate dependencies
[dependencies]
glam = "0.15"
approx = "0.4"
