[package]
name = "oct32norm"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
edition = "2018"
license = "MIT"

[lib]
name = "oct32norm"
path = "src/lib.rs"

[dev-dependencies]
proptest = "0.8"
bencher = "0.1.5"
rand = "0.6"

[[bench]]
name = "bench"
harness = false