#![allow(dead_code)]
#![allow(clippy::cast_lossless)]
#![allow(clippy::excessive_precision)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::needless_return)]

// Include the file generated by the build.rs script
include!(concat!(env!("OUT_DIR"), "/halton.rs"));
